common:
        http_server: 
                enabled: true
                host: '127.0.0.1'
                port: '8081'   
        socket_server:
                enabled: true
                host: 'localhost'
                port: '8082'
        web_socket": 
                enabled: false
                token: ''
                url: '/ws'

specific:
        token: '12345'
        mongo: 
                atlas: false
                user: ''
                pass: ''
                host: '127.0.0.1'
                port: '27017'
                database: 'test'
                collection: 'test'  